### ISSUE TITLE
[META] New routes

### ISSUE THREAD

**Issue by franklinchou** [franklinchou/Millennial-Falcon#23]
- [x] `DELETE  /features/:id               controllers.FeatureController.delete(id: String)`
- [x] `DELETE  /users/:id/feature          controllers.UserController.removeFeatures(id: String)`
- [ ] `DELETE  /groups/:id/feature         controllers.GroupController.removeFeatures(id: String)`
- [x] `POST    /users/:id/features         controllers.UserController.associateFeatures(id: String)` #28
- [x] `POST    /groups/:id/features        controllers.GroupController.associateFeatures(id: String)`
